openrouter:
  api_key: "sk-or-v1-xxxxxxx"

  models:
    # Default models for each agent type
    planner: "mistralai/mistral-small-3.2-24b-instruct"
    summarizer: "mistralai/mistral-small-3.2-24b-instruct"
    general_analyst: "mistralai/mistral-small-3.2-24b-instruct"
    business_analyst: "mistralai/mistral-small-3.2-24b-instruct"
    financial_strength_analyst: "mistralai/mistral-small-3.2-24b-instruct"
    moat_analyst: "mistralai/mistral-small-3.2-24b-instruct"
    growth_analyst: "mistralai/mistral-small-3.2-24b-instruct"
    profitability_analyst: "mistralai/mistral-small-3.2-24b-instruct"
    
    # Alternative models from different providers
    alternatives:
      fast: "anthropic/claude-3.5-sonnet"
      reasoning: "openai/o1-mini"
      cost_effective: "google/gemini-1.5-flash"
      advanced: "anthropic/claude-3.5-sonnet"

brave:
  token: "xxxxxx"

# Checkpoint configuration (optional)
checkpoint:
  enabled: false                    # Enable/disable state checkpointing
  base_dir: ".dean_state"          # Directory to store checkpoint files
  keep_checkpoints: 10             # Number of checkpoints to keep per run
  keep_runs: 5                     # Number of old runs to keep
  auto_cleanup: true               # Automatically cleanup old files
  save_on_error: true              # Save checkpoints even on errors
  save_individual_steps: true      # Save individual step results
