models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo

rails:
  input:
    flows:
      - user_intent_check
      - refuse_non_analytical_requests
      - sensitive_data_input_check

  output:
    flows:
      - sensitive_data_output_check
      - output_length_check
      - detailed_summary_check

prompts:
  - task: self_check_summary_quality
    output_parser: yes_no
    content: |
      You are an impartial judge evaluating the quality of a summary.
      The user asked for a summary of a document or text.
      The bot provided the following summary: "{{ last_bot_utterance }}"
      
      Consider the following criteria:
      1. Key Points: Does the summary cover the most important points of the original content?
      2. Sufficiency: Is the summary detailed enough to be useful, or is it too vague or superficial?
      3. Conciseness: Is the summary to the point, without unnecessary jargon or repetition (while still being sufficiently detailed)?
      4. Relevance: Is the summary relevant to a typical request for analyzing financial or business data?
      
      Based on these criteria, would you say this summary is of good quality and provides sufficient detail?
      Answer with only "yes" or "no".
