models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo

rails:
  input:
    flows:
      - mask sensitive data on input 

  output:
    flows:
      - self check facts         
      - self check hallucination 

config:
  sensitive_data_detection:
    input:
      entities:
        - PERSON       
        - EMAIL_ADDRESS 

prompts:
  - task: output_parser_check 
    content: |
      You are an expert analyst.
      Your task is to process the user's request.
      You MUST only return a JSON object with a single key 'summary'.
      The value of the 'summary' key should be a concise summary of the input document or text provided by the user.
      The summary must not be empty.
      The summary must be at most 500 characters long.
      Do not include any other text, explanations, or formatting outside of this JSON object.

  - task: self_check_facts  
    output_parser: yes_no
    content: |
      Your task is to check if the last statement made by the bot is factually correct.
      The last statement is: "{{ last_bot_utterance }}"
      Is the statement factually correct?
      Answer Yes or No.

  - task: self_check_hallucination  
    content: |
      Is the last bot utterance making up information or hallucinating?
      The last bot utterance is: "{{ last_bot_utterance }}"
      Answer Yes or No.